import React from 'react';

interface AboutModalProps {
  isOpen: boolean;
  onClose: () => void;
}

const AboutModal: React.FC<AboutModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) {
    return null;
  }

  return (
    <div 
      className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4" 
      role="dialog" 
      aria-modal="true"
      aria-labelledby="about-modal-title"
      onClick={onClose}
    >
      <div 
        className="bg-white dark:bg-gray-800 rounded-lg shadow-2xl w-full max-w-lg max-h-[90vh] flex flex-col relative"
        onClick={(e) => e.stopPropagation()} // Prevent closing when clicking inside the modal
      >
        <header className="p-4 border-b border-gray-200 dark:border-gray-700 flex justify-between items-center">
          <h2 id="about-modal-title" className="text-xl font-bold text-gray-800 dark:text-gray-100">About AI Dermatologist</h2>
          <button
            onClick={onClose}
            className="p-2 rounded-full text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700"
            aria-label="Close about modal"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </header>

        <div className="flex-grow p-6 overflow-y-auto space-y-4 text-gray-700 dark:text-gray-300">
          <p>
            <strong>AI Dermatologist</strong> is an innovative tool designed to provide a preliminary analysis of skin lesions using advanced artificial intelligence. By uploading a photo, you can receive an AI-powered assessment that identifies potential conditions.
          </p>

          <div className="bg-yellow-100 dark:bg-yellow-900/30 border-l-4 border-yellow-500 dark:border-yellow-600 text-yellow-700 dark:text-yellow-200 p-4 rounded-md" role="alert">
            <p className="font-bold">Crucial Medical Disclaimer</p>
            <p className="text-sm">This application is for informational and educational purposes only. The analysis provided is generated by an AI and is <strong>not a substitute for professional medical advice, diagnosis, or treatment.</strong> Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.</p>
          </div>

          <p>
            This project leverages the power of Google's Gemini API to analyze images and provide structured, insightful feedback.
          </p>
          
          <div>
            <p className="font-semibold text-gray-800 dark:text-gray-200">Created by:</p>
            <p>Vicente C. Cavalida Jr. MD</p>
          </div>
        </div>

        <footer className="p-4 border-t border-gray-200 dark:border-gray-700 flex justify-between items-center">
          <div className="text-xs text-gray-400 dark:text-gray-500">
            <p>Version 1.0.1</p>
            <p>Build: 20240722.1</p>
          </div>
          <button
            onClick={onClose}
            className="px-6 py-2 font-semibold text-white bg-blue-600 rounded-md shadow-sm hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
          >
            Close
          </button>
        </footer>
      </div>
    </div>
  );
};

export default AboutModal;
